declare function getType(payload: any): string;
declare function isUndefined(payload: any): payload is undefined;
declare function isNull(payload: any): payload is null;
declare function isObject(payload: any): payload is object;
declare function isFunction(payload: any): payload is Function;
declare function isArray(payload: any): payload is any[];
declare function isString(payload: any): payload is string;
declare function isNumber(payload: any): payload is number;
declare function isBoolean(payload: any): payload is boolean;
declare function isRegExp(payload: any): payload is RegExp;
declare function isDate(payload: any): payload is Date;
export { getType, isUndefined, isNull, isObject, isFunction, isArray, isString, isNumber, isBoolean, isRegExp, isDate };
