name: Publish npm
on:
  release:
    types: published
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - if: '!github.event.release.prerelease'
        run: npm dist-tag add "$(npm view . name)@$(npm view . version)" latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
