name: Test
on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
      - '*rc'
      - '*.config.*'
      - '*.json'
      - '*.lock'
      - .github/workflows/test-js.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - test/**
      - '*rc'
      - '*.config.*'
      - '*.json'
      - '*.lock'
      - .github/workflows/test-js.yml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test-nodejs:
    strategy:
      matrix:
        node-version: ['16', '18', '20']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
  # test-deno:
  # test-bun:
